---
docker:
  host: "https://boot2docker:2376"
  ssl_verify_peer: false

stacks:
  - name: "common"
    description: "Common units for all stacks"
    units:
      - name: "base"
        version: 1.0.0
        dockerfile: "common/Dockerfile"
        startable: false

  - name: "routing"
    description: "Load balancing and proxying"
    units:
      - name: "load-balancer"
        version: 1.0.0
        dockerfile: "load-balancer/Dockerfile"
        ports:
          - 8888:80
        dependant_unit_names:
          - "common:base"
          - "proxy1"
          - "proxy2"

      - name: "proxy"
        instances: 2
        version: 1.0.0
        dockerfile: "proxy/Dockerfile"
        dependant_unit_names:
          - common:base
          - app:app1
          - app:app2

  - name: "app"
    description: "The Application"
    units:
      - name: "app"
        instances: 2
        version: 1.0.0
        dockerfile: "app/Dockerfile"
        dependant_unit_names:
          - "common:base"
